### ISSUE TITLE
Can we tracking users edits?

### ISSUE THREAD

**Issue by skmar** [azgs/az-wine#9]
Hi @jessica-azgs and @Lbookman 

Is is not something needed right away but is there a way we can easily track changes made by users? Or see which users are making changes?

--Stephanie

@fmichaelconway

**Comment by jessicagood** [comment]
See answers to @ridavis's issue [here](https://github.com/azgs/azwinemap/issues/4). That's not going to show changes by user exactly, rather changes as whole - though since users can only change the data for businesses they own it should be almost obvious which user made the change.

I haven't found a way to watch changes within the structure of the framework that was used for this app.

**Comment by skmar** [comment]
Ahh, thanks. I'm using [Page Monitor for Chrome](https://chrome.google.com/webstore/detail/page-monitor/pemhgklkefakciniebenbfclihhmmfcd) on the [data](http://winedb.arizonaexperience.org/api/rest/vineyards) and map.
